apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.resources.kube.redpanda.com
spec:
  group: resources.kube.redpanda.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  version: v1